# SPDX-FileCopyrightText: 2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "xrpicker-egui"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = {version = "0.21.3", features = ["persistence"]}
egui-winit = {version = "0.21.1", default-features = false, features = ["wayland"]}
image = {version = "0.24.5", default-features = false, features = ["png"]}
itertools = "0.10.5"
xrpicker = {path = "../xrpicker-core"}
