# SPDX-FileCopyrightText: 2022-2023, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

[package]
description = "Choose your active OpenXR runtime"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "xrpicker-gui"
version = "2.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = {version = "0.21.3", features = ["persistence"]}
egui-winit = {version = "0.21.1", default-features = false, features = ["wayland"]}
image = {version = "0.24.5", default-features = false, features = ["png"]}
itertools = "0.10.5"
rfd = "0.11.2"
xrpicker = {path = "../xrpicker-core"}

# To add icon to EXE
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
LegalCopyright = "Copyright © 2022-2023, Collabora, Ltd."
OriginalFilename = "xrpicker-gui.exe"
